FROM weisburd/str-analysis@sha256:69f989a7e6e34a34c7aee126f9501caaa49ba879464577ca07dae6ac73b213b9

#RUN python3 -m pip install --no-cache-dir git+https://github.com/broadinstitute/str-analysis

COPY scripts /scripts

#COPY paper/compare_catalogs.py /paper/compare_catalogs.py

