FROM weisburd/str-analysis@sha256:13fda540973ff2bec7789464344416397f3225d168cd79889e9277904e7062ef

RUN python3 -m pip install --no-cache-dir git+https://github.com/broadinstitute/str-analysis

COPY scripts /scripts
#COPY paper/compare_catalogs.py /paper/compare_catalogs.py

