#!/bin/bash
#
# Generate the ExtendedBoundaries source catalog.
#
# The gap-purity rule in str_analysis.extend_str_catalog_boundaries widens a tandem repeat locus
# outward into its flanking sequence for as long as the flank keeps matching the locus's own motif.
# The EP400 locus is the motivating example, described in
# https://gnomad.broadinstitute.org/news/2026-07-str-data-update/
#
# Running the rule over the whole v2 catalog yields a set of wider definitions for loci whose
# boundaries stopped short of the repeat they sit in. --only-output-extended-loci writes just those
# new definitions, leaving out every locus that came from v2, so the result is a source catalog of
# loci to add to v2 rather than a replacement for it. A new definition is dropped when v2 already
# describes the same repeat, so nothing here duplicates v2.
#
# This is run once, by hand, and its output is fed to run_all_steps_to_generate_the_catalog.py via
# --extended-loci-catalog. It is kept out of that script because the input is the finished v2
# catalog, so the result is fixed rather than something each pipeline run should recompute.
#
# Loci whose motif contains IUPAC codes (GCN and the like) are never extended: such a motif stands
# for a set of sequences rather than one, so it matches flanking sequence that a concrete motif
# would not, and the rule would read that as the repeat continuing.
#
# Usage:  cd extended_loci && ./generate_extended_loci_catalog.sh /path/to/hg38.fa

set -euo pipefail

REFERENCE_FASTA="${1:-../hg38.fa}"
V2_CATALOG_URL="https://storage.googleapis.com/tandem-repeat-catalog/v2.0/TRExplorer.repeat_catalog_v2.hg38.1_to_1000bp_motifs.bed.gz"
V2_CATALOG="$(basename "${V2_CATALOG_URL}")"
OUTPUT="TRExplorer.extended_loci_v2.1.hg38.bed.gz"

if [ ! -f "${REFERENCE_FASTA}" ]; then
    echo "Reference fasta not found: ${REFERENCE_FASTA}" >&2
    exit 1
fi

if [ ! -f "${V2_CATALOG}" ]; then
    wget -O "${V2_CATALOG}.tmp" -q "${V2_CATALOG_URL}"
    mv "${V2_CATALOG}.tmp" "${V2_CATALOG}"
fi

# Defaults for the rule's three parameters are used deliberately: --max-repeats-in-gap 2,
# --min-purity-of-new-sequence 0.9 (matching ExpansionHunter's own threshold for calling a read
# repetitive) and --min-reference-purity 0.9.
# Record which str-analysis produced the output. The rule's behaviour has changed before, and a
# catalog generated by an older version is indistinguishable from a current one by inspection, so
# this is the only thing that says which is which. It is written to PROVENANCE.txt rather than the
# log because the log, like the catalog itself, is covered by this repo's .gitignore, so nothing in
# git would otherwise record the rule version the pipeline's default input came from.
STR_ANALYSIS_DIR="$(python3 -c 'import str_analysis, os; print(os.path.dirname(os.path.dirname(str_analysis.__file__)))')"
{
    echo "generated_by:            extended_loci/generate_extended_loci_catalog.sh"
    echo "output:                  ${OUTPUT}"
    echo "input_catalog:           ${V2_CATALOG_URL}"
    echo "str_analysis_dir:        ${STR_ANALYSIS_DIR}"
    echo "str_analysis_revision:   $(git -C "${STR_ANALYSIS_DIR}" rev-parse HEAD 2>/dev/null || echo unknown)"
    echo "str_analysis_uncommitted: $(git -C "${STR_ANALYSIS_DIR}" status --porcelain 2>/dev/null | wc -l | tr -d ' ') file(s)"
    echo "rule_parameters:         defaults (--max-repeats-in-gap 2, --min-purity-of-new-sequence 0.9, --min-reference-purity 0.9)"
} > PROVENANCE.txt
cat PROVENANCE.txt

python3 -u -m str_analysis.extend_str_catalog_boundaries \
    --only-output-extended-loci \
    --reference-fasta "${REFERENCE_FASTA}" \
    --output-path "${OUTPUT}" \
    "${V2_CATALOG}" 2>&1 | tee generate_extended_loci_catalog.log

echo "Wrote ${OUTPUT}"
